# Generated by Django 5.0.6 on 2024-06-30 04:51

import django.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_account', models.CharField(max_length=15)),
                ('to_account', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account_owner', models.OneToOneField(null=True, on_delete=django.db.models.fields.CharField, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
