# Generated by Django 5.0.6 on 2024-07-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='loan_approv',
            new_name='loan_approve',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposite'), (2, 'withdrawal'), (3, 'Loan'), (4, 'Loan paid'), (5, 'Transfer Out'), (6, 'Transfer In')], null=True),
        ),
    ]
